title: Home
author: Alexander van Meegen
email: a.van.meegen@fz-juelich.de
# description: A rudimentary personal webpage.

github_username: alexvanmeegen
# linkedin_username: alexander-van-meegen
twitter_username: alexvanmeegen

show_excerpts: false

header_pages:
  - research.md
  - teaching.md
  - cv.md

theme: minima

plugins:
 - jekyll-seo-tag
