title: Home
author: Alexander van Meegen
email: a.van.meegen@fz-juelich.de
description: A rudimentary personal webpage.

google_analytics: UA-145007308-1

minima:
  social_links:
    github: alexvanmeegen
    linkedin: alexander-van-meegen
    twitter: alexvanmeegen

show_excerpts: false

header_pages:
  - research.md
  - teaching.md
  - cv.md

remote_theme: jekyll/minima

plugins:
  - jekyll-sitemap
