title: Home
author:
  name: Alexander van Meegen
  email: avanmeegen@fas.harvard.edu
description: More Is Different

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

google_analytics: UA-145007308-1

minima:
  social_links:
    github: alexvanmeegen
    linkedin: alexander-van-meegen
    twitter: alexvanmeegen

show_excerpts: false

header_pages:
  - research.md
  - teaching.md
  - cv.md

remote_theme: jekyll/minima

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
