title: Home
author:
  name: Alexander van Meegen
  email: alexander.vanmeegen@epfl.ch
description: >
  Theory of Neural Networks (how the heck do they work?)

google_analytics: G-MY9YFCGP0Q

theme: minima

sass:
  quiet_deps: true
  silence_deprecations: [import]

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic
  show_excerpts: false
  hide_site_feed_link: true
  nav_pages:
    - research.md
    - teaching.md
    - cv.md
  date_format: "%d.%b.%Y"
  social_links:
    - title: Scholar
      icon: google-scholar
      url: "https://scholar.google.com/citations?user=2HpXCQ0AAAAJ"
    - title: Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/avm.bsky.social"
    - title: X
      icon: x-twitter
      url: "https://twitter.com/alexvanmeegen"
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/alexander-van-meegen"
    - title: Github
      icon: github
      url: "https://github.com/alexvanmeegen"
